---
:base_url: https://lirias2repo.kuleuven.be/elements-cache/rest/publications?per-page=10&affected-since=
:base_delete_url: https://lirias2repo.kuleuven.be/elements-cache/rest/deleted/publications?per-page=10&deleted-since=
:user: limoapi
:password: 17v&WM5XcOAaT3Ll
:last_run_updates: '2018-03-04T12:07:59.28+01:00'
:last_run_deletes: '2018-06-25T16:02:00.520Z'
